In [2]:
import pandas as pd
import numpy as np

file_path = "raw_Ops_data/Operational_Mining_Data.xlsx"

# Extract every sheet from the operational data
sheets = pd.read_excel(file_path, sheet_name=None)

In [3]:
# See what we received which is our source sheet-inventory
print(sheets.keys())

dict_keys(['START_HERE', 'Equipment_Events', 'Delays_Downtime', 'Operator_Activities', 'Shift_Performance', 'Safety_Observations', 'Training_Records', 'Maintenance_Notifications', 'Environmental_Readings', 'Access_Control', 'Data_Dictionary'])

In [4]:
#targeted sheet inventory for operational data
operational_sheets = [
    "Equipment_Events",
    "Delays_Downtime",
    "Operator_Activities",
    "Shift_Performance",
    "Safety_Observations",
    "Training_Records",
    "Maintenance_Notifications",
    "Environmental_Readings",
    "Access_Control"
]

data_dictionary = sheets["Data_Dictionary"]

In [5]:
datasets = {
    name: sheets[name]
    for name in operational_sheets
}

In [6]:
dict = {}
for name, df in datasets.items():
    print(f"{name}: {df.shape}")
    dict[name] = df.shape

Equipment_Events: (46, 11)
Delays_Downtime: (46, 11)
Operator_Activities: (46, 15)
Shift_Performance: (46, 15)
Safety_Observations: (46, 13)
Training_Records: (46, 14)
Maintenance_Notifications: (46, 14)
Environmental_Readings: (46, 11)
Access_Control: (46, 12)

In [7]:

print(f"Data extraction completed successfully. \n {dict}")

pd.DataFrame.from_dict(dict, orient='index', columns=['Rows', 'Columns']).to_csv("data_inventory/dataset_shapes.csv")

Data extraction completed successfully.
 {'Equipment_Events': (46, 11), 'Delays_Downtime': (46, 11), 'Operator_Activities': (46, 15), 'Shift_Performance': (46, 15), 'Safety_Observations': (46, 13), 'Training_Records': (46, 14), 'Maintenance_Notifications': (46, 14), 'Environmental_Readings': (46, 11), 'Access_Control': (46, 12)}

In [8]:
#data sheet inventory list extraction with statistical descriptive data
inventory = []

for name, df in datasets.items():

    inventory.append({
        "Dataset": name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Duplicate_Rows_Detected": int(df.duplicated().sum()),
        "Total_Missing_Values": int(df.isna().sum().sum()),
        "Missing_Value_Pct(%)": round(
            df.isna().sum().sum() / df.size * 100, 2
        )
    })

inventory_df = pd.DataFrame(inventory)
inventory_df.to_csv('data_inventory/datasheet_Highlevel_inventory.csv')
inventory_df

,Dataset,Rows,Columns,Duplicate_Rows_Detected,Total_Missing_Values,Missing_Value_Pct(%)
0,Equipment_Events,46,11,1,16,3.16
1,Delays_Downtime,46,11,1,26,5.14
2,Operator_Activities,46,15,1,7,1.01
3,Shift_Performance,46,15,1,8,1.16
4,Safety_Observations,46,13,1,63,10.54
5,Training_Records,46,14,1,15,2.33
6,Maintenance_Notifications,46,14,1,1,0.16
7,Environmental_Readings,46,11,1,23,4.55
8,Access_Control,46,12,1,16,2.90

In [9]:
#define column level analysis through column-level profiling

column_profiles = []

for data_sheet_name, df in datasets.items():
    for column in df.columns:

        series = df[column]

        column_profiles.append({
            "Dataset": data_sheet_name,
            "Column": column,
            "Data_Type": str(series.dtype),
            "Row_Count": len(series),
            "Missing_Count": int(series.isna().sum()),
            "Missing_Pct": round(series.isna().mean() * 100, 2),
            "Unique_Count": int(series.nunique(dropna=True)),
            "Duplicate_Value_Count": int(
                series.duplicated(keep=False).sum()
            ),
            "Sample_Values": " | ".join(
                series.dropna()
                .astype(str)
                .head(3)
                .tolist()
            )
        })
        
column_profile_df = pd.DataFrame(column_profiles)

column_profile_df.to_csv('data_inventory/datasheet-column-level.csv')

column_profile_df

#please install data wrangler extension for a better tabular experience

,Dataset,Column,Data_Type,Row_Count,Missing_Count,Missing_Pct,Unique_Count,Duplicate_Value_Count,Sample_Values
0,Equipment_Events,Event_ID,object,46,0,0.00,45,2,EVT0001 | EVT0002 | EVT0003
1,Equipment_Events,Equipment_Name,object,46,1,2.17,19,40,TRK-001 | TRK002 | truck03
2,Equipment_Events,Event_Time,object,46,0,0.00,45,2,01/07/2026 11:00 | 07/01/2026 04:00 PM | 2026/...
3,Equipment_Events,Event_Type,object,46,0,0.00,7,45,Idle | start | Inspection
4,Equipment_Events,Status,object,46,0,0.00,4,46,Complete | Open | Complete
...,...,...,...,...,...,...,...,...,...
111,Access_Control,Access_Result,object,46,0,0.00,3,46,granted | Granted | Denied
112,Access_Control,Reason,object,46,15,32.61,3,46,Anti-passback | Anti-passback | Expired training
113,Access_Control,Contractor_Group,object,46,0,0.00,3,46,Contractor-B | Contractor-A | Contractor-C
114,Access_Control,Home_Zone,object,46,0,0.00,4,46,Zone-West | Zone-East | Zone-South
115,Access_Control,Device_ID,object,46,0,0.00,4,46,DEV-2 | DEV-3 | DEV-4

In [10]:
# analyse the data for identifier columns
id_columns = [
    column
    for data_sheet_name, df in datasets.items()
    for column in df.columns
    if column.endswith("_ID")
]

pd.Series(id_columns, name="Identifier_Column").to_csv('data_inventory/identifier_columns.csv', index=False)

id_columns

['Event_ID',
 'Operator_ID',
 'Delay_ID',
 'Operator_ID',
 'Activity_ID',
 'Operator_ID',
 'Supervisor_ID',
 'Shift_Record_ID',
 'Operator_ID',
 'Observation_ID',
 'Reporter_ID',
 'Observed_Person_ID',
 'Training_Record_ID',
 'Operator_ID',
 'Notification_ID',
 'Work_Order_ID',
 'Reading_ID',
 'Sensor_ID',
 'Access_Event_ID',
 'Badge_ID',
 'Employee_ID',
 'Device_ID']

In [11]:
#for a more clear approach we would need to know which ID belongs to which table, so we need to do a table/sheet-level extraction of ID'series
for data_sheet_name, df in datasets.items():

    candidate_ids = [
        column for column in df.columns
        if column.endswith("_ID")
    ]

    print(f"\n{data_sheet_name}")
    print(candidate_ids)

#from our earlier visual/excel analysis of the data, we saw that Equipment_Name is actually tied to another table, (where the equipment_name column could possibly be our ID in the Equipments table).
#we can now see the relational data structure of the dataset provided and how each table links

Equipment_Events
['Event_ID', 'Operator_ID']

Delays_Downtime
['Delay_ID', 'Operator_ID']

Operator_Activities
['Activity_ID', 'Operator_ID', 'Supervisor_ID']

Shift_Performance
['Shift_Record_ID', 'Operator_ID']

Safety_Observations
['Observation_ID', 'Reporter_ID', 'Observed_Person_ID']

Training_Records
['Training_Record_ID', 'Operator_ID']

Maintenance_Notifications
['Notification_ID', 'Work_Order_ID']

Environmental_Readings
['Reading_ID', 'Sensor_ID']

Access_Control
['Access_Event_ID', 'Badge_ID', 'Employee_ID', 'Device_ID']

In [12]:
#in this function we focus on extracting all the Identifiers and candidate_keys or foreign_keys

for data_sheet_name, df in datasets.items():

    candidate_ids = [
        column for column in df.columns
        if column.endswith("_ID")
    ]

    print(f"\n{data_sheet_name}")
    
    for column in candidate_ids:

        duplicate_count = df[column].duplicated().sum()
        missing_count = df[column].isna().sum()

        print(
            f"{column}: "
            f"duplicates={duplicate_count}, "
            f"missing={missing_count}"
        )
        
#if our identifier returns a duplicate>0 then it rejects the ACID principle/ and violates the unique identifier constraint

Equipment_Events
Event_ID: duplicates=1, missing=0
Operator_ID: duplicates=38, missing=0

Delays_Downtime
Delay_ID: duplicates=1, missing=0
Operator_ID: duplicates=38, missing=0

Operator_Activities
Activity_ID: duplicates=1, missing=0
Operator_ID: duplicates=37, missing=1
Supervisor_ID: duplicates=43, missing=0

Shift_Performance
Shift_Record_ID: duplicates=1, missing=0
Operator_ID: duplicates=38, missing=0

Safety_Observations
Observation_ID: duplicates=1, missing=0
Reporter_ID: duplicates=43, missing=0
Observed_Person_ID: duplicates=38, missing=0

Training_Records
Training_Record_ID: duplicates=1, missing=0
Operator_ID: duplicates=38, missing=0

Maintenance_Notifications
Notification_ID: duplicates=1, missing=0
Work_Order_ID: duplicates=1, missing=0

Environmental_Readings
Reading_ID: duplicates=1, missing=0
Sensor_ID: duplicates=41, missing=0

Access_Control
Access_Event_ID: duplicates=1, missing=0
Badge_ID: duplicates=37, missing=1
Employee_ID: duplicates=37, missing=0
Device_ID: duplicates=42, missing=0

In [13]:
for data_sheet_name, df in datasets.items():

    numeric_df = df.select_dtypes(include=np.number)

    print(f"===== {data_sheet_name} =====")

    if numeric_df.empty:
        print("No numeric columns")
    else:
        display(numeric_df.describe().T)
        numeric_df.describe().T.to_csv(f'data_inventory/{data_sheet_name}_numeric_profile.csv')

===== Equipment_Events =====

,count,mean,std,min,25%,50%,75%,max
Meter_Reading,46.0,22881.302174,147269.689798,1007.3,1083.95,1171.55,1253.675,999999.0

===== Delays_Downtime =====

          count        mean         std   min  25%   50%   75%      max
Duration   45.0  371.883333  2139.18906 -45.0  2.0  45.0  90.0  14400.0

===== Operator_Activities =====

          count  mean        std  min  25%  50%  75%    max
Quantity   46.0  16.0  65.471962  2.0  4.0  6.0  9.5  450.0

===== Shift_Performance =====

,count,mean,std,min,25%,50%,75%,max
Scheduled_Hours,46.0,12.000000,0.000000,12.00,12.000,12.000,12.0000,12.00
Actual_Hours,46.0,10.239130,2.693076,8.00,9.000,10.000,11.0000,26.00
Loads,46.0,29.391304,7.889454,-3.00,26.000,29.000,35.7500,40.00
Tonnes,46.0,2731.521739,604.935138,1615.00,2401.250,2720.000,3296.2500,3800.00
Fuel_Used,46.0,615.021739,157.293002,0.00,507.750,628.500,703.5000,849.00
Availability_Pct,46.0,0.846087,0.124908,0.70,0.740,0.805,0.9250,1.35
Utilisation_Pct,46.0,0.755435,0.098086,0.62,0.655,0.755,0.8475,0.93

===== Safety_Observations =====
No numeric columns
===== Training_Records =====

       count       mean        std   min   25%   50%    75%    max
Score   46.0  76.913043  17.129346  42.0  65.0  77.5  86.75  145.0

===== Maintenance_Notifications =====

                count      mean       std  min  25%  50%  75%   max
Downtime_Hours   46.0  3.891304  3.640685 -4.0  2.0  2.0  8.0  18.0

===== Environmental_Readings =====

       count        mean          std   min   25%    50%     75%     max
Value   46.0  240.921739  1471.079208 -25.0  3.71  11.14  32.075  9999.0

===== Access_Control =====
No numeric columns

In [14]:
# Example: percentage fields
for data_sheet_name, df in datasets.items():

    for column in ["Availability_Pct(%)", "Utilisation_Pct(%)"]:

        if column in df.columns:

            invalid = df[
                (df[column] < 0) |
                (df[column] > 100)
            ]

            print(
                data_sheet_name,
                column,
                "invalid values:",
                len(invalid)
            )
            invalid.to_csv(f'data_inventory/{data_sheet_name}_{column}_invalid_percentage_values.csv', index=False)

In [15]:


for data_sheet_name, df in datasets.items():

    categorical_columns = df.select_dtypes(
        include=["object", "string"]
    ).columns

    print(f"\n===== {data_sheet_name} =====")

    for column in categorical_columns:

        unique_values = df[column].dropna().unique()

        print(
            f"{column}: "
            f"{len(unique_values)} unique values"
        )

        print(unique_values[:20])
        
#analyzed the and profiled categorical columns(no dates included) to have a better view at incorrect category labels

===== Equipment_Events =====
Event_ID: 45 unique values
['EVT0001' 'EVT0002' 'EVT0003' 'EVT0004' 'EVT0005' 'EVT0006' 'EVT0007'
 'EVT0008' 'EVT0009' 'EVT0010' 'EVT0011' 'EVT0012' 'EVT0013' 'EVT0014'
 'EVT0015' 'EVT0016' 'EVT0017' 'EVT0018' 'EVT0019' 'EVT0020']
Equipment_Name: 19 unique values
['TRK-001' 'TRK002' 'truck03' 'EXC001' 'EXC-02' 'Drill 01' 'TRK-003'
 'Excavator 1' 'Truck 1' 'Truck 2' 'Truck 3' 'DRL001' 'TRK003' 'EX 001'
 'truck01' 'EXC-01' 'EXC002' 'TRK 001' 'truck02']
Event_Time: 45 unique values
['01/07/2026 11:00' '07/01/2026 04:00 PM' '2026/07/01 21:00'
 '2026-07-02 02:00:00' '02/07/2026 07:00' '07/02/2026 12:00 PM'
 '2026/07/02 17:00' '2026-07-02 22:00:00' '03/07/2026 03:00'
 '07/03/2026 08:00 AM' '2026/07/03 13:00' '2026-07-03 18:00:00'
 '03/07/2026 23:00' '07/04/2026 04:00 AM' '2026/07/04 09:00'
 '2026-07-04 14:00:00' '04/07/2026 19:00' '07/05/2026 12:00 AM'
 '2026/07/05 05:00' '2026-07-05 10:00:00']
Event_Type: 7 unique values
['Idle' 'start' 'Inspection' 'Fault' 'Stop' 'Start' 'Strat']
Status: 4 unique values
['Complete' 'Open' 'closed' 'Closed']
Meter_Unit: 2 unique values
['hours' 'mins']
Location: 3 unique values
['Workshop' 'South Pit' 'North Pit']
Operator_ID: 8 unique values
['OP1001' 'OP1002' 'OP1003' 'OP1004' 'OP1005' 'OP1006' 'OP1007' 'OP1008']
Source_System: 1 unique values
['Telemetry-A']
Comment: 3 unique values
['check sensor' 'Normal event' 'reset after comms loss']

===== Delays_Downtime =====
Delay_ID: 45 unique values
['DLY0001' 'DLY0002' 'DLY0003' 'DLY0004' 'DLY0005' 'DLY0006' 'DLY0007'
 'DLY0008' 'DLY0009' 'DLY0010' 'DLY0011' 'DLY0012' 'DLY0013' 'DLY0014'
 'DLY0015' 'DLY0016' 'DLY0017' 'DLY0018' 'DLY0019' 'DLY0020']
Equipment_Name: 20 unique values
['TRK-002' 'truck03' 'EX 001' 'EXC-02' 'DRL001' 'truck01' 'Truck 2'
 'EXC001' 'Excavator 2' 'DRILL-1' 'TRK 001' 'TRK002' 'TRK-003' 'EXC-01'
 'Truck 1' 'truck02' 'Truck 3' 'EXC002' 'Excavator 1' 'TRK003']
Start_Time: 45 unique values
['01/07/2026 12:00' '07/01/2026 06:00 PM' '2026/07/02 00:00'
 '2026-07-02 06:00:00' '02/07/2026 12:00' '07/02/2026 06:00 PM'
 '2026/07/03 00:00' '2026-07-03 06:00:00' '03/07/2026 12:00'
 '07/03/2026 06:00 PM' '2026/07/04 00:00' '2026-07-04 06:00:00'
 '04/07/2026 12:00' '07/04/2026 06:00 PM' '2026/07/05 00:00'
 '2026-07-05 06:00:00' '05/07/2026 12:00' '07/05/2026 06:00 PM'
 '2026/07/06 00:00' '2026-07-06 06:00:00']
End_Time: 45 unique values
['07/01/2026 12:45 PM' '2026/07/01 18:30' '2026-07-02 00:45:00'
 '02/07/2026 08:00' '07/02/2026 01:30 PM' '2026/07/02 19:00'
 '2026-07-03 00:30:00' '03/07/2026 06:15' '07/03/2026 11:30 AM'
 '2026/07/03 19:00' '2026-07-04 01:00:00' '04/07/2026 06:45'
 '07/04/2026 02:00 PM' '2026/07/04 18:45' '2026-07-05 00:30:00'
 '05/07/2026 06:30' '07/05/2026 12:45 PM' '2026/07/05 20:00'
 '2026-07-06 01:30:00' '06/07/2026 08:00']
Duration_Unit: 2 unique values
['minutes' 'hours']
Delay_Category: 7 unique values
['Weather' 'mechanical' 'Other' 'No Operator' 'Mechanical' 'Operational'
 'Mecanical']
Cause_Code: 4 unique values
['UNK' 'ENV' 'OPS' 'ENG']
Operator_ID: 8 unique values
['OP1002' 'OP1003' 'OP1004' 'OP1005' 'OP1006' 'OP1007' 'OP1008' 'OP1001']
Approved_By: 2 unique values
['SUP01' 'SUP02']
Comment: 4 unique values
['unknown' 'awaiting spares' 'rain delay' 'operator reported vibration']

===== Operator_Activities =====
Activity_ID: 45 unique values
['ACT0001' 'ACT0002' 'ACT0003' 'ACT0004' 'ACT0005' 'ACT0006' 'ACT0007'
 'ACT0008' 'ACT0009' 'ACT0010' 'ACT0011' 'ACT0012' 'ACT0013' 'ACT0014'
 'ACT0015' 'ACT0016' 'ACT0017' 'ACT0018' 'ACT0019' 'ACT0020']
Operator_ID: 8 unique values
['OP1002' 'OP1003' 'OP1004' 'OP1005' 'OP1006' 'OP1007' 'OP1008' 'OP1001']
Operator_Name: 8 unique values
['Aisha Naidoo' 'Thabo Dlamini' 'Mia Jacobs' 'Kagiso Molefe'
 'Zanele Ncube' 'Noah Smith' 'Ayanda Khumalo' 'Lebo Mokoena']
Email: 8 unique values
['aisha.naidoo@example.test' 'thabo.dlamini@example.test'
 'mia.jacobs@example.test' 'kagiso.molefe@example.test'
 'zanele.ncube@example.test' 'noah.smith@example.test'
 'ayanda.khumalo@example.test' 'lebo.mokoena@example.test']
Mobile_Number: 8 unique values
['082-555-0102' '0835550103' '060 555 0104' '0795550105' '072 555 0106'
 '0845550107' '076-555-0108' '071 555 0101']
Home_Zone: 4 unique values
['Zone-West' 'Zone-East' 'Zone-South' 'Zone-North']
Contractor_Group: 3 unique values
['Contractor-B' 'Contractor-A' 'Contractor-C']
Equipment_Name: 20 unique values
['TRK-002' 'TRK003' 'EXC-01' 'Excavator 2' 'DRILL-1' 'TRK001' 'TRK002'
 'TRK-003' 'EX 001' 'EXC-02' 'DRL001' 'truck01' 'truck03' 'EXC002'
 'Drill 01' 'truck02' 'TRK 001' 'EXC001' 'TRK099' 'Truck 1']
Activity_Start: 45 unique values
['01/07/2026 11:00' '07/01/2026 04:00 PM' '2026/07/01 21:00'
 '2026-07-02 02:00:00' '02/07/2026 07:00' '07/02/2026 12:00 PM'
 '2026/07/02 17:00' '2026-07-02 22:00:00' '03/07/2026 03:00'
 '07/03/2026 08:00 AM' '2026/07/03 13:00' '2026-07-03 18:00:00'
 '03/07/2026 23:00' '07/04/2026 04:00 AM' '2026/07/04 09:00'
 '2026-07-04 14:00:00' '04/07/2026 19:00' '07/05/2026 12:00 AM'
 '2026/07/05 05:00' '2026-07-05 10:00:00']
Activity_End: 45 unique values
['2026/07/01 15:00' '2026-07-01 19:00:00' '01/07/2026 23:00'
 '07/02/2026 05:00 AM' '2026/07/02 10:00' '2026-07-02 13:00:00'
 '02/07/2026 19:00' '07/03/2026 01:00 AM' '2026/07/03 06:00'
 '2026-07-03 11:00:00' '03/07/2026 16:00' '07/03/2026 08:00 PM'
 '2026/07/03 21:00' '2026-07-04 05:00:00' '04/07/2026 11:00'
 '07/04/2026 03:00 PM' '2026/07/04 21:00' '2026-07-05 03:00:00'
 '05/07/2026 06:00' '07/05/2026 11:00 AM']
Activity_Type: 5 unique values
['Hauling' 'Break' 'hualing' 'Loading' 'Inspection']
Quantity_Unit: 2 unique values
['loads' 'tonnes']
Supervisor_ID: 3 unique values
['SUP01' 'SUP03' 'SUP02']
Comment: 3 unique values
['productive shift' 'route congested' 'new operator pairing']

===== Shift_Performance =====
Shift_Record_ID: 45 unique values
['SHF0001' 'SHF0002' 'SHF0003' 'SHF0004' 'SHF0005' 'SHF0006' 'SHF0007'
 'SHF0008' 'SHF0009' 'SHF0010' 'SHF0011' 'SHF0012' 'SHF0013' 'SHF0014'
 'SHF0015' 'SHF0016' 'SHF0017' 'SHF0018' 'SHF0019' 'SHF0020']
Shift_Date: 44 unique values
['01/07/2026' '07/01/2026' '2026/07/02' '2026-07-02' '03/07/2026'
 '07/03/2026' '2026/07/04' '2026-07-04' '05/07/2026' '07/05/2026'
 '2026/07/06' '2026-07-06' '07/07/2026' '2026/07/08' '2026-07-08'
 '09/07/2026' '07/09/2026' '2026/07/10' '2026-07-10' '11/07/2026']
Shift_Code: 2 unique values
['Day' 'Night']
Crew: 3 unique values
['Charlie' 'Alpha' 'Bravo']
Equipment_Name: 18 unique values
['TRK002' 'TRK-003' 'EXC-01' 'Excavator 2' 'DRILL-1' 'Truck 1' 'EX 001'
 'TRK001' 'Truck 2' 'Truck 3' 'EXC002' 'DRL001' 'TRK-002' 'Excavator 1'
 'EXC-02' 'Drill 01' 'TRK003' 'truck01']
Operator_ID: 8 unique values
['OP1002' 'OP1003' 'OP1004' 'OP1005' 'OP1006' 'OP1007' 'OP1008' 'OP1001']
Fuel_Unit: 2 unique values
['litres' 'gallons']
Supervisor_Comment: 4 unique values
['Road wet' 'Older equipment allocated' 'Short staffed'
 'Normal conditions']

===== Safety_Observations =====
Observation_ID: 45 unique values
['SAF0001' 'SAF0002' 'SAF0003' 'SAF0004' 'SAF0005' 'SAF0006' 'SAF0007'
 'SAF0008' 'SAF0009' 'SAF0010' 'SAF0011' 'SAF0012' 'SAF0013' 'SAF0014'
 'SAF0015' 'SAF0016' 'SAF0017' 'SAF0018' 'SAF0019' 'SAF0020']
Observation_Date: 45 unique values
['01/07/2026 15:00' '07/02/2026 12:00 AM' '2026/07/02 09:00'
 '2026-07-02 18:00:00' '03/07/2026 03:00' '07/03/2026 12:00 PM'
 '2026/07/03 21:00' '2026-07-04 06:00:00' '04/07/2026 15:00'
 '07/05/2026 12:00 AM' '2026/07/05 09:00' '2026-07-05 18:00:00'
 '06/07/2026 03:00' '07/06/2026 12:00 PM' '2026/07/06 21:00'
 '2026-07-07 06:00:00' '07/07/2026 15:00' '07/08/2026 12:00 AM'
 '2026/07/08 09:00' '2026-07-08 18:00:00']
Reporter_ID: 3 unique values
['OP1001' 'SUP01' 'SUP02']
Observed_Person_ID: 8 unique values
['OP1002' 'OP1003' 'OP1004' 'OP1005' 'OP1006' 'OP1007' 'OP1008' 'OP1001']
Equipment_Name: 21 unique values
['truck02' 'Truck 3' 'EXC001' 'EXC-02' 'Drill 01' 'truck01' 'TRK003'
 'EX 001' 'DRL001' 'TRK-001' 'Truck 2' 'truck03' 'EXC002' 'DRILL-1'
 'Excavator 1' 'Truck 1' 'TRK002' 'TRK-003' 'Excavator 2' 'TRK001']
Category: 7 unique values
['Saftey' 'PPE' 'Vehicle Interaction' 'Housekeeping' 'Procedure'
 'Production' 'Environmental']
Severity: 5 unique values
['low' 'Low' 'Medium' 'High' 'Critical']
Location: 3 unique values
['South Pit' 'Workshop' 'North Pit']
Description: 5 unique values
['Good housekeeping noted' 'Seatbelt compliance observed'
 'Loose material near walkway' 'Visibility reduced by dust'
 'OP1004 ignored procedure again']
Immediate_Action: 3 unique values
['Coaching provided' 'Logged for review' 'Area isolated']
Status: 3 unique values
['In Review' 'Open' 'Closed']
Closed_Date: 14 unique values
['07/05/2026 03:00 AM' '07/01/2026 12:00 PM' '2026-07-05 21:00:00'
 '06/07/2026 06:00' '07/06/2026 03:00 PM' '2026-07-07 09:00:00'
 '2026/07/08 12:00' '2026-07-08 21:00:00' '2026/07/10 00:00'
 '2026-07-10 09:00:00' '13/07/2026 18:00' '07/14/2026 03:00 AM'
 '2026/07/17 12:00' '19/07/2026 18:00']
Attachment_Name: 2 unique values
['obs-note.pdf' 'photo_01.jpg']

===== Training_Records =====
Training_Record_ID: 45 unique values
['TRN0001' 'TRN0002' 'TRN0003' 'TRN0004' 'TRN0005' 'TRN0006' 'TRN0007'
 'TRN0008' 'TRN0009' 'TRN0010' 'TRN0011' 'TRN0012' 'TRN0013' 'TRN0014'
 'TRN0015' 'TRN0016' 'TRN0017' 'TRN0018' 'TRN0019' 'TRN0020']
Operator_ID: 8 unique values
['OP1002' 'OP1003' 'OP1004' 'OP1005' 'OP1006' 'OP1007' 'OP1008' 'OP1001']
Operator_Name: 8 unique values
['Aisha Naidoo' 'Thabo Dlamini' 'Mia Jacobs' 'Kagiso Molefe'
 'Zanele Ncube' 'Noah Smith' 'Ayanda Khumalo' 'Lebo Mokoena']
Course_Code: 4 unique values
['SAFE01' 'EQP02' 'DATA01' 'SAFE-1']
Course_Name: 3 unique values
['Operational Safety' 'Mobile Equipment' 'Data Awareness']
Completion_Date: 45 unique values
['16/01/2025' '01/31/2025' '2025/02/15' '2025-03-02' '17/03/2025'
 '04/01/2025' '2025/04/16' '2025-05-01' '16/05/2025' '05/31/2025'
 '2025/06/15' '2025-06-30' '15/07/2025' '07/30/2025' '2025/08/14'
 '2025-08-29' '13/09/2025' '09/28/2025' '2025/10/13' '2025-10-28']
Expiry_Date: 45 unique values
['01/16/2027' '2027/01/31' '2027-02-15' '02/03/2027' '03/17/2027'
 '2027/04/01' '2027-04-16' '11/04/2025' '05/16/2027' '2027/05/31'
 '2027-06-15' '30/06/2027' '07/15/2027' '2027/07/30' '2027-08-14'
 '29/08/2027' '09/13/2027' '2027/09/28' '2027-10-13' '28/10/2027']
Result: 2 unique values
['Pass' 'Fail']
Provider: 3 unique values
['Provider A' 'Provider B' 'Internal']
Certificate_Number: 45 unique values
['CERT-00001' 'CERT-00002' 'CERT-00003' 'CERT-00004' 'CERT-00005'
 'CERT-00006' 'CERT-00007' 'CERT-00008' 'CERT-00009' 'CERT-00010'
 'CERT-00011' 'CERT-00012' 'CERT-00013' 'CERT-00014' 'CERT-00015'
 'CERT-00016' 'CERT-00017' 'CERT-00018' 'CERT-00019' 'CERT-00020']
Medical_Fitness_Code: 3 unique values
['MF-R' 'MF-B' 'MF-A']
Home_Zone: 4 unique values
['Zone-West' 'Zone-East' 'Zone-South' 'Zone-North']
Comment: 2 unique values
['Uploaded manually' 'Refresher required']

===== Maintenance_Notifications =====
Notification_ID: 45 unique values
['MNT0001' 'MNT0002' 'MNT0003' 'MNT0004' 'MNT0005' 'MNT0006' 'MNT0007'
 'MNT0008' 'MNT0009' 'MNT0010' 'MNT0011' 'MNT0012' 'MNT0013' 'MNT0014'
 'MNT0015' 'MNT0016' 'MNT0017' 'MNT0018' 'MNT0019' 'MNT0020']
Equipment_Name: 21 unique values
['TRK-002' 'TRK003' 'Excavator 1' 'Excavator 2' 'DRILL-1' 'TRK 001'
 'TRK002' 'Truck 3' 'EXC-02' 'DRL001' 'Truck 1' 'EX 001' 'Truck One'
 'EXC001' 'Drill 01' 'TRK-001' 'Truck 2' 'EXC-01' 'TRK001' 'truck03']
Raised_Date: 45 unique values
['01/07/2026 13:00' '07/01/2026 08:00 PM' '2026/07/02 03:00'
 '2026-07-02 10:00:00' '02/07/2026 17:00' '07/03/2026 12:00 AM'
 '2026/07/03 07:00' '2026-07-03 14:00:00' '03/07/2026 21:00'
 '07/04/2026 04:00 AM' '2026/07/04 11:00' '2026-07-04 18:00:00'
 '05/07/2026 01:00' '07/05/2026 08:00 AM' '2026/07/05 15:00'
 '2026-07-05 22:00:00' '06/07/2026 05:00' '07/06/2026 12:00 PM'
 '2026/07/06 19:00' '2026-07-07 02:00:00']
Priority: 4 unique values
['P1' 'P2' 'P3' 'Urgent']
Notification_Type: 4 unique values
['break down' 'Planned' 'Inspection' 'Breakdown']
Fault_Code: 4 unique values
['ELC03' 'ENG01' 'UNK' 'HYD02']
Description: 4 unique values
['Scheduled service' 'Hydraulic leak' 'High temperature warning'
 'Intermittent sensor alarm']
Reported_By: 3 unique values
['OP1001' 'SUP01' 'SYSTEM']
Planned_Start: 45 unique values
['07/02/2026 01:00 PM' '2026/07/02 20:00' '2026-07-03 03:00:00'
 '03/07/2026 10:00' '07/03/2026 05:00 PM' '2026/07/04 00:00'
 '2026-07-04 07:00:00' '04/07/2026 14:00' '07/04/2026 09:00 PM'
 '2026/07/05 04:00' '2026-07-05 11:00:00' '05/07/2026 18:00'
 '07/06/2026 01:00 AM' '2026/07/06 08:00' '2026-07-06 15:00:00'
 '06/07/2026 22:00' '07/07/2026 05:00 AM' '2026/07/07 12:00'
 '2026-07-07 19:00:00' '08/07/2026 02:00']
Actual_Start: 45 unique values
['2026/07/02 13:00' '2026-07-03 04:00:00' '03/07/2026 01:00'
 '07/03/2026 10:00 AM' '2026/07/03 17:00' '2026-07-04 08:00:00'
 '04/07/2026 07:00' '07/04/2026 05:00 PM' '2026/07/05 05:00'
 '2026-07-05 12:00:00' '05/07/2026 09:00' '07/01/2026 06:00 PM'
 '2026/07/06 04:00' '2026-07-06 16:00:00' '06/07/2026 15:00'
 '07/06/2026 08:00 PM' '2026/07/07 03:00' '2026-07-07 12:00:00'
 '07/07/2026 19:00' '07/08/2026 05:00 AM']
Actual_End: 44 unique values
['2026-07-02 15:00:00' '03/07/2026 06:00' '07/03/2026 02:00 AM'
 '2026/07/03 14:00' '2026-07-03 18:00:00' '04/07/2026 09:00'
 '07/04/2026 03:00 PM' '2026/07/04 21:00' '2026-07-05 07:00:00'
 '05/07/2026 13:00' '07/05/2026 11:00 AM' '2026/07/06 04:00'
 '2026-07-06 06:00:00' '06/07/2026 20:00' '07/06/2026 11:00 PM'
 '2026/07/07 04:00' '2026-07-07 04:00:00' '07/07/2026 14:00'
 '07/07/2026 11:00 PM' '2026/07/08 07:00']
Work_Order_ID: 45 unique values
['WO-10001' 'WO-10002' 'WO-10003' 'WO-10004' 'WO-10005' 'WO-10006'
 'WO-10007' 'WO-10008' 'WO-10009' 'WO-10010' 'WO-10011' 'WO-10012'
 'WO-10013' 'WO-10014' 'WO-10015' 'WO-10016' 'WO-10017' 'WO-10018'
 'WO-10019' 'WO-10020']
Status: 3 unique values
['In Progress' 'Open' 'Closed']

===== Environmental_Readings =====
Reading_ID: 45 unique values
['ENV0001' 'ENV0002' 'ENV0003' 'ENV0004' 'ENV0005' 'ENV0006' 'ENV0007'
 'ENV0008' 'ENV0009' 'ENV0010' 'ENV0011' 'ENV0012' 'ENV0013' 'ENV0014'
 'ENV0015' 'ENV0016' 'ENV0017' 'ENV0018' 'ENV0019' 'ENV0020']
Reading_Time: 45 unique values
['01/07/2026 09:00' '07/01/2026 12:00 PM' '2026/07/01 15:00'
 '2026-07-01 18:00:00' '01/07/2026 21:00' '07/02/2026 12:00 AM'
 '2026/07/02 03:00' '2026-07-02 06:00:00' '02/07/2026 09:00'
 '07/02/2026 12:00 PM' '2026/07/02 15:00' '2026-07-02 18:00:00'
 '02/07/2026 21:00' '07/03/2026 12:00 AM' '2026/07/03 03:00'
 '2026-07-03 06:00:00' '03/07/2026 09:00' '07/03/2026 12:00 PM'
 '2026/07/03 15:00' '2026-07-03 18:00:00']
Sensor_ID: 5 unique values
['SNS-02' 'SNS-03' 'SNS-04' 'SNS-05' 'SNS-01']
Location: 3 unique values
['North Pit' 'South Pit' 'Workshop']
Reading_Type: 4 unique values
['Rainfall' 'Temperature' 'Noise' 'Dust']
Unit: 5 unique values
['mm' 'C' 'dB' 'ppm' 'mg/m3']
Quality_Flag: 3 unique values
['Good' 'Suspect' 'Estimated']
Equipment_Nearby: 21 unique values
['TRK-002' 'truck03' 'EXC001' 'EXC-02' 'Drill 01' 'truck01' 'TRK002'
 'EX 001' 'EXC002' 'DRL001' 'TRK001' 'Truck 2' 'TRK003' 'EXC-01'
 'Excavator 2' 'DRILL-1' 'TRK 001' 'truck02' 'Truck 3' 'Excavator 1']
Calibration_Due: 45 unique values
['02/08/2026' '08/03/2026' '2026/08/04' '2026-08-05' '06/08/2026'
 '08/07/2026' '2026/08/08' '2026-08-09' '10/08/2026' '08/11/2026'
 '2026/08/12' '2026-08-13' '14/08/2026' '08/15/2026' '2026/08/16'
 '2026-08-17' '18/08/2026' '08/19/2026' '2026/08/20' '2026-08-21']
Comment: 3 unique values
['manual capture' 'windy conditions' 'sensor cleaned']

===== Access_Control =====
Access_Event_ID: 45 unique values
['ACC0001' 'ACC0002' 'ACC0003' 'ACC0004' 'ACC0005' 'ACC0006' 'ACC0007'
 'ACC0008' 'ACC0009' 'ACC0010' 'ACC0011' 'ACC0012' 'ACC0013' 'ACC0014'
 'ACC0015' 'ACC0016' 'ACC0017' 'ACC0018' 'ACC0019' 'ACC0020']
Event_Time: 45 unique values
['01/07/2026 10:00' '07/01/2026 02:00 PM' '2026/07/01 18:00'
 '2026-07-01 22:00:00' '02/07/2026 02:00' '07/02/2026 06:00 AM'
 '2026/07/02 10:00' '2026-07-02 14:00:00' '02/07/2026 18:00'
 '07/02/2026 10:00 PM' '2026/07/03 02:00' '2026-07-03 06:00:00'
 '03/07/2026 10:00' '07/03/2026 02:00 PM' '2026/07/03 18:00'
 '2026-07-03 22:00:00' '04/07/2026 02:00' '07/04/2026 06:00 AM'
 '2026/07/04 10:00' '2026-07-04 14:00:00']
Badge_ID: 8 unique values
['BDG-1001' 'BDG-1002' 'BDG-1003' 'BDG-1004' 'BDG-1005' 'BDG-1006'
 'BDG-1007' 'BDG-1000']
Employee_ID: 9 unique values
['OP1002' 'OP1003' 'OP1004' 'OP1005' 'OP1006' 'OP1007' 'OP1008' 'OP1001'
 'OP9999']
Employee_Name: 8 unique values
['Aisha Naidoo' 'Thabo Dlamini' 'Mia Jacobs' 'Kagiso Molefe'
 'Zanele Ncube' 'Noah Smith' 'Ayanda Khumalo' 'Lebo Mokoena']
Access_Point: 3 unique values
['Main Gate' 'Plant Turnstile' 'Workshop Gate']
Direction: 4 unique values
['OUT' 'Entry' 'Exit' 'IN']
Access_Result: 3 unique values
['granted' 'Granted' 'Denied']
Reason: 3 unique values
['Anti-passback' 'Expired training' 'Valid badge']
Contractor_Group: 3 unique values
['Contractor-B' 'Contractor-A' 'Contractor-C']
Home_Zone: 4 unique values
['Zone-West' 'Zone-East' 'Zone-South' 'Zone-North']
Device_ID: 4 unique values
['DEV-2' 'DEV-3' 'DEV-4' 'DEV-1']

In [16]:
#extracting date/time-like columns
for data_sheet_name, df in datasets.items():

    date_columns = [
        column for column in df.columns
        if any(
            keyword in column.lower()
            for keyword in [
                "date",
                "time",
                "start",
                "end",
                "expiry",
                "completion"
            ]
        )
    ]

    print(data_sheet_name, date_columns)
    
    #raw-value inpsection after date/time-like column extraction 

    for column in date_columns:

        print(f"\n{data_sheet_name} -> {column}")

        print(
            df[column]
            .dropna()
            .astype(str)
            .head(10)
            .tolist()
        )

Equipment_Events ['Event_Time']

Equipment_Events -> Event_Time
['01/07/2026 11:00', '07/01/2026 04:00 PM', '2026/07/01 21:00', '2026-07-02 02:00:00', '02/07/2026 07:00', '07/02/2026 12:00 PM', '2026/07/02 17:00', '2026-07-02 22:00:00', '03/07/2026 03:00', '07/03/2026 08:00 AM']
Delays_Downtime ['Start_Time', 'End_Time']

Delays_Downtime -> Start_Time
['01/07/2026 12:00', '07/01/2026 06:00 PM', '2026/07/02 00:00', '2026-07-02 06:00:00', '02/07/2026 12:00', '07/02/2026 06:00 PM', '2026/07/03 00:00', '2026-07-03 06:00:00', '03/07/2026 12:00', '07/03/2026 06:00 PM']

Delays_Downtime -> End_Time
['07/01/2026 12:45 PM', '2026/07/01 18:30', '2026-07-02 00:45:00', '02/07/2026 08:00', '07/02/2026 01:30 PM', '2026/07/02 19:00', '2026-07-03 00:30:00', '03/07/2026 06:15', '07/03/2026 11:30 AM', '2026/07/03 19:00']
Operator_Activities ['Activity_Start', 'Activity_End']

Operator_Activities -> Activity_Start
['01/07/2026 11:00', '07/01/2026 04:00 PM', '2026/07/01 21:00', '2026-07-02 02:00:00', '02/07/2026 07:00', '07/02/2026 12:00 PM', '2026/07/02 17:00', '2026-07-02 22:00:00', '03/07/2026 03:00', '07/03/2026 08:00 AM']

Operator_Activities -> Activity_End
['2026/07/01 15:00', '2026-07-01 19:00:00', '01/07/2026 23:00', '07/02/2026 05:00 AM', '2026/07/02 10:00', '2026-07-02 13:00:00', '02/07/2026 19:00', '07/03/2026 01:00 AM', '2026/07/03 06:00', '2026-07-03 11:00:00']
Shift_Performance ['Shift_Date']

Shift_Performance -> Shift_Date
['01/07/2026', '07/01/2026', '2026/07/02', '2026-07-02', '03/07/2026', '07/03/2026', '2026/07/04', '2026-07-04', '05/07/2026', '07/05/2026']
Safety_Observations ['Observation_Date', 'Closed_Date']

Safety_Observations -> Observation_Date
['01/07/2026 15:00', '07/02/2026 12:00 AM', '2026/07/02 09:00', '2026-07-02 18:00:00', '03/07/2026 03:00', '07/03/2026 12:00 PM', '2026/07/03 21:00', '2026-07-04 06:00:00', '04/07/2026 15:00', '07/05/2026 12:00 AM']

Safety_Observations -> Closed_Date
['07/05/2026 03:00 AM', '07/01/2026 12:00 PM', '2026-07-05 21:00:00', '06/07/2026 06:00', '07/06/2026 03:00 PM', '2026-07-07 09:00:00', '2026/07/08 12:00', '2026-07-08 21:00:00', '2026/07/10 00:00', '2026-07-10 09:00:00']
Training_Records ['Completion_Date', 'Expiry_Date']

Training_Records -> Completion_Date
['16/01/2025', '01/31/2025', '2025/02/15', '2025-03-02', '17/03/2025', '04/01/2025', '2025/04/16', '2025-05-01', '16/05/2025', '05/31/2025']

Training_Records -> Expiry_Date
['01/16/2027', '2027/01/31', '2027-02-15', '02/03/2027', '03/17/2027', '2027/04/01', '2027-04-16', '11/04/2025', '05/16/2027', '2027/05/31']
Maintenance_Notifications ['Raised_Date', 'Planned_Start', 'Actual_Start', 'Actual_End', 'Downtime_Hours']

Maintenance_Notifications -> Raised_Date
['01/07/2026 13:00', '07/01/2026 08:00 PM', '2026/07/02 03:00', '2026-07-02 10:00:00', '02/07/2026 17:00', '07/03/2026 12:00 AM', '2026/07/03 07:00', '2026-07-03 14:00:00', '03/07/2026 21:00', '07/04/2026 04:00 AM']

Maintenance_Notifications -> Planned_Start
['07/02/2026 01:00 PM', '2026/07/02 20:00', '2026-07-03 03:00:00', '03/07/2026 10:00', '07/03/2026 05:00 PM', '2026/07/04 00:00', '2026-07-04 07:00:00', '04/07/2026 14:00', '07/04/2026 09:00 PM', '2026/07/05 04:00']

Maintenance_Notifications -> Actual_Start
['2026/07/02 13:00', '2026-07-03 04:00:00', '03/07/2026 01:00', '07/03/2026 10:00 AM', '2026/07/03 17:00', '2026-07-04 08:00:00', '04/07/2026 07:00', '07/04/2026 05:00 PM', '2026/07/05 05:00', '2026-07-05 12:00:00']

Maintenance_Notifications -> Actual_End
['2026-07-02 15:00:00', '03/07/2026 06:00', '07/03/2026 02:00 AM', '2026/07/03 14:00', '2026-07-03 18:00:00', '04/07/2026 09:00', '07/04/2026 03:00 PM', '2026/07/04 21:00', '2026-07-05 07:00:00', '05/07/2026 13:00']

Maintenance_Notifications -> Downtime_Hours
['2', '2', '1', '4', '1', '1', '-4', '4', '2', '1']
Environmental_Readings ['Reading_Time']

Environmental_Readings -> Reading_Time
['01/07/2026 09:00', '07/01/2026 12:00 PM', '2026/07/01 15:00', '2026-07-01 18:00:00', '01/07/2026 21:00', '07/02/2026 12:00 AM', '2026/07/02 03:00', '2026-07-02 06:00:00', '02/07/2026 09:00', '07/02/2026 12:00 PM']
Access_Control ['Event_Time']

Access_Control -> Event_Time
['01/07/2026 10:00', '07/01/2026 02:00 PM', '2026/07/01 18:00', '2026-07-01 22:00:00', '02/07/2026 02:00', '07/02/2026 06:00 AM', '2026/07/02 10:00', '2026-07-02 14:00:00', '02/07/2026 18:00', '07/02/2026 10:00 PM']

In [17]:
#raw-value inpsection after date/time-like column extraction 
for dataset_name, df in datasets.items():

    date_columns = [
        column for column in df.columns
        if any(
            keyword in column.lower()
            for keyword in [
                "date",
                "time",
                "start",
                "end",
                "expiry",
                "completion"
            ]
        )
    ]

    for column in date_columns:

        print(f"\n{dataset_name} -> {column}")

        print(
            df[column]
            .dropna()
            .astype(str)
            .head(10)
            .tolist()
        )

Equipment_Events -> Event_Time
['01/07/2026 11:00', '07/01/2026 04:00 PM', '2026/07/01 21:00', '2026-07-02 02:00:00', '02/07/2026 07:00', '07/02/2026 12:00 PM', '2026/07/02 17:00', '2026-07-02 22:00:00', '03/07/2026 03:00', '07/03/2026 08:00 AM']

Delays_Downtime -> Start_Time
['01/07/2026 12:00', '07/01/2026 06:00 PM', '2026/07/02 00:00', '2026-07-02 06:00:00', '02/07/2026 12:00', '07/02/2026 06:00 PM', '2026/07/03 00:00', '2026-07-03 06:00:00', '03/07/2026 12:00', '07/03/2026 06:00 PM']

Delays_Downtime -> End_Time
['07/01/2026 12:45 PM', '2026/07/01 18:30', '2026-07-02 00:45:00', '02/07/2026 08:00', '07/02/2026 01:30 PM', '2026/07/02 19:00', '2026-07-03 00:30:00', '03/07/2026 06:15', '07/03/2026 11:30 AM', '2026/07/03 19:00']

Operator_Activities -> Activity_Start
['01/07/2026 11:00', '07/01/2026 04:00 PM', '2026/07/01 21:00', '2026-07-02 02:00:00', '02/07/2026 07:00', '07/02/2026 12:00 PM', '2026/07/02 17:00', '2026-07-02 22:00:00', '03/07/2026 03:00', '07/03/2026 08:00 AM']

Operator_Activities -> Activity_End
['2026/07/01 15:00', '2026-07-01 19:00:00', '01/07/2026 23:00', '07/02/2026 05:00 AM', '2026/07/02 10:00', '2026-07-02 13:00:00', '02/07/2026 19:00', '07/03/2026 01:00 AM', '2026/07/03 06:00', '2026-07-03 11:00:00']

Shift_Performance -> Shift_Date
['01/07/2026', '07/01/2026', '2026/07/02', '2026-07-02', '03/07/2026', '07/03/2026', '2026/07/04', '2026-07-04', '05/07/2026', '07/05/2026']

Safety_Observations -> Observation_Date
['01/07/2026 15:00', '07/02/2026 12:00 AM', '2026/07/02 09:00', '2026-07-02 18:00:00', '03/07/2026 03:00', '07/03/2026 12:00 PM', '2026/07/03 21:00', '2026-07-04 06:00:00', '04/07/2026 15:00', '07/05/2026 12:00 AM']

Safety_Observations -> Closed_Date
['07/05/2026 03:00 AM', '07/01/2026 12:00 PM', '2026-07-05 21:00:00', '06/07/2026 06:00', '07/06/2026 03:00 PM', '2026-07-07 09:00:00', '2026/07/08 12:00', '2026-07-08 21:00:00', '2026/07/10 00:00', '2026-07-10 09:00:00']

Training_Records -> Completion_Date
['16/01/2025', '01/31/2025', '2025/02/15', '2025-03-02', '17/03/2025', '04/01/2025', '2025/04/16', '2025-05-01', '16/05/2025', '05/31/2025']

Training_Records -> Expiry_Date
['01/16/2027', '2027/01/31', '2027-02-15', '02/03/2027', '03/17/2027', '2027/04/01', '2027-04-16', '11/04/2025', '05/16/2027', '2027/05/31']

Maintenance_Notifications -> Raised_Date
['01/07/2026 13:00', '07/01/2026 08:00 PM', '2026/07/02 03:00', '2026-07-02 10:00:00', '02/07/2026 17:00', '07/03/2026 12:00 AM', '2026/07/03 07:00', '2026-07-03 14:00:00', '03/07/2026 21:00', '07/04/2026 04:00 AM']

Maintenance_Notifications -> Planned_Start
['07/02/2026 01:00 PM', '2026/07/02 20:00', '2026-07-03 03:00:00', '03/07/2026 10:00', '07/03/2026 05:00 PM', '2026/07/04 00:00', '2026-07-04 07:00:00', '04/07/2026 14:00', '07/04/2026 09:00 PM', '2026/07/05 04:00']

Maintenance_Notifications -> Actual_Start
['2026/07/02 13:00', '2026-07-03 04:00:00', '03/07/2026 01:00', '07/03/2026 10:00 AM', '2026/07/03 17:00', '2026-07-04 08:00:00', '04/07/2026 07:00', '07/04/2026 05:00 PM', '2026/07/05 05:00', '2026-07-05 12:00:00']

Maintenance_Notifications -> Actual_End
['2026-07-02 15:00:00', '03/07/2026 06:00', '07/03/2026 02:00 AM', '2026/07/03 14:00', '2026-07-03 18:00:00', '04/07/2026 09:00', '07/04/2026 03:00 PM', '2026/07/04 21:00', '2026-07-05 07:00:00', '05/07/2026 13:00']

Maintenance_Notifications -> Downtime_Hours
['2', '2', '1', '4', '1', '1', '-4', '4', '2', '1']

Environmental_Readings -> Reading_Time
['01/07/2026 09:00', '07/01/2026 12:00 PM', '2026/07/01 15:00', '2026-07-01 18:00:00', '01/07/2026 21:00', '07/02/2026 12:00 AM', '2026/07/02 03:00', '2026-07-02 06:00:00', '02/07/2026 09:00', '07/02/2026 12:00 PM']

Access_Control -> Event_Time
['01/07/2026 10:00', '07/01/2026 02:00 PM', '2026/07/01 18:00', '2026-07-01 22:00:00', '02/07/2026 02:00', '07/02/2026 06:00 AM', '2026/07/02 10:00', '2026-07-02 14:00:00', '02/07/2026 18:00', '07/02/2026 10:00 PM']

In [18]:
missing_profile = []

for dataset_name, df in datasets.items():

    for column in df.columns:

        missing = df[column].isna().sum()

        missing_profile.append({
            "Dataset": dataset_name,
            "Column": column,
            "Missing_Count": int(missing),
            "Total_Rows": len(df),
            "Missing_Pct(%)": round(
                missing / len(df) * 100, 2
            )
        })

missing_profile_df = pd.DataFrame(missing_profile)

missing_profile_df = missing_profile_df.sort_values(
    ["Dataset", "Missing_Pct(%)"],
    ascending=[True, False]
)

missing_profile_df.to_csv('data_inventory/missing-value_profile.csv')

missing_profile_df

,Dataset,Column,Missing_Count,Total_Rows,Missing_Pct(%)
112,Access_Control,Reason,15,46,32.61
106,Access_Control,Badge_ID,1,46,2.17
104,Access_Control,Access_Event_ID,0,46,0.00
105,Access_Control,Event_Time,0,46,0.00
107,Access_Control,Employee_ID,0,46,0.00
...,...,...,...,...,...
73,Training_Records,Score,0,46,0.00
74,Training_Records,Provider,0,46,0.00
75,Training_Records,Certificate_Number,0,46,0.00
76,Training_Records,Medical_Fitness_Code,0,46,0.00
77,Training_Records,Home_Zone,0,46,0.00

In [19]:
text_columns = []

for data_sheet_name, df in datasets.items():

    for column in df.columns:

        if df[column].dtype == "object" or pd.api.types.is_string_dtype(df[column]):

            text_columns.append({
                "Dataset": data_sheet_name,
                "Column": column,
                "Unique_Count": df[column].nunique(),
                "Avg_Text_Length": round(
                    df[column]
                    .dropna()
                    .astype(str)
                    .str.len()
                    .mean(),
                    2
                )
            })

text_profile_df = pd.DataFrame(text_columns)

missing_profile_df.to_csv('data_inventory/Free-text_inventory.csv')
text_profile_df.to_csv('data_inventory/Free-text_inventory.csv', index=False)


text_profile_df

              Dataset            Column  Unique_Count  Avg_Text_Length
0    Equipment_Events          Event_ID            45             7.00
1    Equipment_Events    Equipment_Name            19             6.84
2    Equipment_Events        Event_Time            45            17.50
3    Equipment_Events        Event_Type             7             5.59
4    Equipment_Events            Status             4             6.17
..                ...               ...           ...              ...
98     Access_Control     Access_Result             3             6.76
99     Access_Control            Reason             3            13.65
100    Access_Control  Contractor_Group             3            12.00
101    Access_Control         Home_Zone             4             9.48
102    Access_Control         Device_ID             4             5.00

[103 rows x 4 columns]

In [20]:
#lets target PII and more sensitive information at risk, examples include, email, home_zone, employee_name, mobile number and more

privacy_keywords = [
    "name",
    "email",
    "mobile",
    "phone",
    "employee",
    "operator",
    "medical",
    "home",
    "badge"
]

privacy_inventory = []

for dataset_name, df in datasets.items():

    for column in df.columns:

        column_lower = column.lower()

        potential_sensitive = any(
            keyword in column_lower
            for keyword in privacy_keywords
        )

        if potential_sensitive:

            privacy_inventory.append({
                "Dataset": dataset_name,
                "Column": column,
                "Potential_Sensitivity": True
            })

privacy_df = pd.DataFrame(privacy_inventory)

privacy_df.to_csv('data_inventory/privacy_sensitive_fields.csv', index=False)

privacy_df

                      Dataset                Column  Potential_Sensitivity
0            Equipment_Events        Equipment_Name                   True
1            Equipment_Events           Operator_ID                   True
2             Delays_Downtime        Equipment_Name                   True
3             Delays_Downtime           Operator_ID                   True
4         Operator_Activities           Operator_ID                   True
5         Operator_Activities         Operator_Name                   True
6         Operator_Activities                 Email                   True
7         Operator_Activities         Mobile_Number                   True
8         Operator_Activities             Home_Zone                   True
9         Operator_Activities        Equipment_Name                   True
10          Shift_Performance        Equipment_Name                   True
11          Shift_Performance           Operator_ID                   True
12        Safety_Observations        Equipment_Name                   True
13        Safety_Observations       Attachment_Name                   True
14           Training_Records           Operator_ID                   True
15           Training_Records         Operator_Name                   True
16           Training_Records           Course_Name                   True
17           Training_Records  Medical_Fitness_Code                   True
18           Training_Records             Home_Zone                   True
19  Maintenance_Notifications        Equipment_Name                   True
20             Access_Control              Badge_ID                   True
21             Access_Control           Employee_ID                   True
22             Access_Control         Employee_Name                   True
23             Access_Control             Home_Zone                   True

In [21]:
data_dictionary = sheets["Data_Dictionary"]

data_dictionary.to_csv('data_inventory/data_dictionary.csv', index=False)

display(data_dictionary)

,Dataset,Field,Plain-language description,Sensitivity,Expected / canonical guidance
0,All datasets,Record identifier,Unique event or record key,Internal,Should be unique and nonblank
1,All datasets,Date/time fields,Recorded event timestamps,Internal,One consistent timezone and format
2,All datasets,Comment / Description,Human-entered context,Potentially sensitive,"Review for identifiers, allegations and unsupp..."
3,Equipment_Events,Equipment_Name,Asset identifier or alias,Internal,"Canonical examples: TRK001, EXC001"
4,Equipment_Events,Meter_Reading / Meter_Unit,Equipment meter value and unit,Internal,Units must be normalised before comparison
5,Delays_Downtime,Duration / Duration_Unit,Recorded delay magnitude,Internal,Must align with start and end timestamps
6,Delays_Downtime,Delay_Category,Reason grouping,Internal,Use controlled categories
7,Operator_Activities,"Operator_Name, Email, Mobile_Number",Direct identifiers,Personal,Use only if necessary for stated purpose
8,Operator_Activities,"Home_Zone, Contractor_Group",Indirect or proxy attributes,Potentially sensitive,May identify or disadvantage groups
9,Operator_Activities,Quantity / Quantity_Unit,Recorded output quantity,Internal,Do not combine mixed units
10,Shift_Performance,"Availability_Pct, Utilisation_Pct",Operational rates,Internal,Expected range 0% to 100%
11,Shift_Performance,Fuel_Used / Fuel_Unit,Shift fuel usage,Internal,Normalise units
12,Safety_Observations,Observed_Person_ID,Person associated with observation,Personal,Observation is not proof of fault
13,Safety_Observations,Description,Free-text safety narrative,Potentially sensitive,May contain identifiers or allegations
14,Training_Records,Medical_Fitness_Code,Restricted fitness code,Sensitive personal,Do not use without appropriate purpose and aut...
15,Training_Records,Home_Zone,Geographic proxy,Potentially sensitive,May indirectly identify individuals
16,Maintenance_Notifications,Downtime_Hours,Recorded outage duration,Internal,Should reconcile with actual timestamps
17,Environmental_Readings,Value / Unit,Environmental measurement,Internal,Interpret only with matching unit and quality ...
18,Access_Control,"Badge_ID, Employee_ID, Employee_Name",Access and identity data,Personal,Purpose-limit access and avoid unnecessary exp...
19,Access_Control,"Home_Zone, Contractor_Group",Proxy attributes,Potentially sensitive,Do not treat as performance drivers without ju...

generated data quality rules from the above profiling outputs saved in `data_inventory`.

In [22]:
from rule_catalogue_generator import (
    build_rule_catalogue,
    load_inventory_inputs,
    save_rule_catalogue,
    summarise_rule_catalogue,
    validate_rule_catalogue,
)

In [23]:
inventory_inputs = load_inventory_inputs("data_inventory")
inventory_inputs.keys()

dict_keys(['data_inventory_dir', 'column_profile', 'missing_profile', 'highlevel_inventory', 'privacy_inventory', 'data_dictionary', 'numeric_profiles', 'domain_overrides'])

In [24]:
rule_catalogue_df = build_rule_catalogue(inventory_inputs)
rule_catalogue_df.head(20)

,Rule_ID,Dataset,Column,Rule_Type,Valid_Condition,Action,Auto_Correct_Allowed,Severity,Reason,Rule_Source,Evidence
0,DQ-0001,Access_Control,Access_Event_ID,Completeness,Primary identifier must be populated,Flag missing primary identifiers as exceptions,False,Critical,Blank primary identifiers break traceability,Generated from datasheet-column-level.csv,Missing_Count=0
1,DQ-0002,Access_Control,Access_Event_ID,Uniqueness,Identifier should be unique at the dataset grain,Flag duplicate identifiers and retain raw rows...,False,Critical,Primary identifier duplication breaks trusted ...,Generated from datasheet-column-level.csv,Row_Count=46; Unique_Count=45; Duplicate_Value...
2,DQ-0003,Access_Control,Access_Event_ID,Validity,Identifier should match ACC followed by four d...,Flag missing or malformed identifier values,False,High,Identifier format supports row-level audit and...,Generated from datasheet-column-level.csv,Column ends with _ID; Unique_Count=45
3,DQ-0004,Access_Control,Access_Point,Validity,Low-cardinality categorical values should use ...,Standardise known casing or spelling variants ...,True,Medium,Profile shows a small set of repeated categori...,Generated from datasheet-column-level.csv,Unique_Count=3; Sample_Values=Main Gate | Plan...
4,DQ-0005,Access_Control,Access_Result,Validity,Low-cardinality categorical values should use ...,Standardise known casing or spelling variants ...,True,Medium,Profile shows a small set of repeated categori...,Generated from datasheet-column-level.csv,Unique_Count=3; Sample_Values=granted | Grante...
5,DQ-0006,Access_Control,Badge_ID,Completeness,Missing values must be explained by a valid bu...,Flag missing values for review before trusted use,False,High,Profiling detected missing values in this column,Generated from missing-value_profile.csv,Missing_Count=1; Missing_Pct=2.17
6,DQ-0007,Access_Control,Badge_ID,Privacy,Potentially sensitive fields should be purpose...,Flag field for privacy-aware handling in clean...,False,High,"Privacy inventory detected identity, proxy, or...",Generated from privacy_sensitive_fields.csv,Potential_Sensitivity=True
7,DQ-0008,Access_Control,Badge_ID,Validity,Identifier should match BDG dash four digits,Flag missing or malformed identifier values,False,High,Identifier format supports row-level audit and...,Generated from datasheet-column-level.csv,Column ends with _ID; Unique_Count=8
8,DQ-0009,Access_Control,"Badge_ID, Employee_ID, Employee_Name",Data dictionary guidance,Purpose-limit access and avoid unnecessary exp...,Use this guidance to decide whether to auto-co...,False,High,Access and identity data,Generated from data_dictionary.csv,Sensitivity=Personal
9,DQ-0010,Access_Control,Contractor_Group,Validity,Low-cardinality categorical values should use ...,Standardise known casing or spelling variants ...,True,Medium,Profile shows a small set of repeated categori...,Generated from datasheet-column-level.csv,Unique_Count=3; Sample_Values=Contractor-B | C...
10,DQ-0011,Access_Control,Device_ID,Validity,Identifier should match DEV dash digits,Flag missing or malformed identifier values,False,High,Identifier format supports row-level audit and...,Generated from datasheet-column-level.csv,Column ends with _ID; Unique_Count=4
11,DQ-0012,Access_Control,Direction,Validity,Low-cardinality categorical values should use ...,Standardise known casing or spelling variants ...,True,Medium,Profile shows a small set of repeated categori...,Generated from datasheet-column-level.csv,Unique_Count=4; Sample_Values=OUT | Entry | Exit
12,DQ-0013,Access_Control,Employee_ID,Privacy,Potentially sensitive fields should be purpose...,Flag field for privacy-aware handling in clean...,False,High,"Privacy inventory detected identity, proxy, or...",Generated from privacy_sensitive_fields.csv,Potential_Sensitivity=True
13,DQ-0014,Access_Control,Employee_ID,Validity,Identifier should match OP followed by four di...,Flag missing or malformed identifier values,False,High,Identifier format supports row-level audit and...,Generated from datasheet-column-level.csv,Column ends with _ID; Unique_Count=9
14,DQ-0015,Access_Control,Employee_Name,Privacy,Potentially sensitive fields should be purpose...,Flag field for privacy-aware handling in clean...,False,High,"Privacy inventory detected identity, proxy, or...",Generated from privacy_sensitive_fields.csv,Potential_Sensitivity=True
15,DQ-0016,Access_Control,Employee_Name,Validity,Low-cardinality categorical values should use ...,Standardise known casing or spelling variants ...,True,Medium,Profile shows a small set of repeated categori...,Generated from datasheet-column-level.csv,Unique_Count=8; Sample_Values=Aisha Naidoo | T...
16,DQ-0017,Access_Control,Entire row,Uniqueness,Exact duplicate rows should not appear in the ...,Flag duplicate rows and exclude later duplicat...,False,High,Exact duplicate rows can inflate operational c...,Generated from datasheet_Highlevel_inventory.csv,Duplicate_Rows_Detected=1
17,DQ-0018,Access_Control,Event_Time,Validity,Date/time values should parse to a single ISO ...,Standardise parseable values and flag ambiguou...,True,High,Profile shows date/time-like field requiring c...,Generated from datasheet-column-level.csv,Sample_Values=01/07/2026 10:00 | 07/01/2026 02...
18,DQ-0019,Access_Control,Home_Zone,Privacy,Potentially sensitive fields should be purpose...,Flag field for privacy-aware handling in clean...,False,High,"Privacy inventory detected identity, proxy, or...",Generated from privacy_sensitive_fields.csv,Potential_Sensitivity=True
19,DQ-0020,Access_Control,Home_Zone,Validity,Low-cardinality categorical values should use ...,Standardise known casing or spelling variants ...,True,Medium,Profile shows a small set of repeated categori...,Generated from datasheet-column-level.csv,Unique_Count=4; Sample_Values=Zone-West | Zone...

In [25]:
validation_results = validate_rule_catalogue(rule_catalogue_df)
validation_results

                             Check  Passed Details
0         Expected columns present    True      OK
1        Rule_ID values are unique    True       0
2    Required fields are populated    True       0
3  Auto_Correct_Allowed is boolean    True      OK
4        Severity values are valid    True      OK

In [26]:
summary = summarise_rule_catalogue(rule_catalogue_df)
summary

{'rules_by_type': Rule_Type
 Completeness                28
 Consistency                  5
 Data dictionary guidance    20
 Plausibility                14
 Privacy                     24
 Temporal integrity           6
 Uniqueness                  19
 Validity                    84
 Name: count, dtype: int64,
 'rules_by_severity': Severity
 Critical     27
 High        103
 Medium       63
 Low           7
 Name: count, dtype: int64,
 'rules_by_source': Rule_Source
 Generated from Delays_Downtime_numeric_profile.csv                2
 Generated from Environmental_Readings_numeric_profile.csv         2
 Generated from Equipment_Events_numeric_profile.csv               1
 Generated from Maintenance_Notifications_numeric_profile.csv      2
 Generated from Operator_Activities_numeric_profile.csv            1
 Generated from Shift_Performance_numeric_profile.csv              5
 Generated from Training_Records_numeric_profile.csv               1
 Generated from data_dictionary.csv                               20
 Generated from datasheet-column-level.csv                       109
 Generated from datasheet_Highlevel_inventory.csv                  9
 Generated from missing-value_profile.csv                         18
 Generated from privacy_sensitive_fields.csv                      24
 Generated from recognised timestamp column pairs                  6
 Name: count, dtype: int64,
 'auto_correct_allowed': Auto_Correct_Allowed
 False    133
 True      67
 Name: count, dtype: int64}

In [27]:
save_rule_catalogue(
    rule_catalogue_df,
    "data_inventory/data_quality_rule_catalogue.csv",
)

WindowsPath('data_inventory/data_quality_rule_catalogue.csv')

Use the rule catalogue as the control table for deterministic cleaning, standardization, transformation logging, and exception candidate capture because it gives us the complete required catalogues extractions.

In [ ]:
from cleaning_standardization import run_cleaning

In [ ]:
cleaning_outputs = run_cleaning(
    datasets,
    rule_catalogue_path="data_inventory/data_quality_rule_catalogue.csv",
    output_dir="standardized_cleaned_data",
)

In [ ]:
cleaning_outputs["cleaning_summary"]

In [ ]:
cleaning_outputs["transformation_log"].head(20)

In [ ]:
cleaning_outputs["exception_candidates"].head(20)